### ISSUE TITLE
Long time windows crash Sampling Calc

### ISSUE THREAD

**Issue by maxaguirre5** [HeinrichHartmann/HeinrichHartmann.github.io#15]
Issue:

When changing the time window to 1 day the calculator slows down significantly. Time windows greater than 1 day frequently crash the browser tab. This occurs regardless of the other inputs. It seems to be due to the simulation that is always running, if this is torn out then there's still performance hits when increasing time window, but the calculator doesn't crash.

Potential solution:

Making the simulation toggleable. It's great to have, but if you're just looking to get estimates it would be helpful to not risk crashing.

By the way this calculator is awesome!

**Comment by HeinrichHartmann** [comment]
Hey @maxaguirre5 thanks for opening this issue! Glad you enjoyed the calculator. I am not sure when I will get to fixing this, but I appreciate you caring enough to leave this message.

Will keep you posted.

**Comment by HeinrichHartmann** [comment]
Deployed hot fix https://github.com/HeinrichHartmann/HeinrichHartmann.github.io/commit/105a0d8d1f2f028be6292b2bc11c4a07dc8b540f

**Comment by HeinrichHartmann** [comment]
Changed the logic, to automatically skip sampling if the simulation would take too long.

Ideally, we would just move the computation async and let it churn in the background until cancelled. However this is much quicker and works "well enough".
